openapi: 3.0.3
info:
  title: 超級管理員 API
  description: Green Map 超級管理員系統管理 API
  version: 1.0.0

servers:
  - url: https://us-central1-{project-id}.cloudfunctions.net
    description: Firebase Cloud Functions

paths:
  # ============ 使用者權限管理 ============
  /updateAdminClaims:
    post:
      summary: 更新使用者權限
      description: 授予或撤銷使用者的管理員/超級管理員/野外考察夥伴權限
      operationId: updateAdminClaims
      tags:
        - 使用者管理
      security:
        - firebaseAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateClaimsRequest'
      responses:
        '200':
          description: 權限更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: 參數錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: 權限不足（非超級管理員）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '412':
          description: 前置條件失敗（無法撤銷自己權限、至少保留一位超級管理員）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  # ============ 標籤管理 ============
  /deleteTagFromLocations:
    post:
      summary: 刪除標籤並清理關聯
      description: 刪除指定標籤，並從所有使用該標籤的地點移除標籤引用
      operationId: deleteTagFromLocations
      tags:
        - 標籤管理
      security:
        - firebaseAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteTagRequest'
      responses:
        '200':
          description: 刪除成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchOperationResponse'
        '403':
          description: 權限不足（非超級管理員）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: 標籤不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    firebaseAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Firebase ID Token（須具有 isSuperAdmin custom claim）

  schemas:
    # ============ 使用者權限 ============
    UpdateClaimsRequest:
      type: object
      required:
        - targetUserId
        - claimType
        - grant
      properties:
        targetUserId:
          type: string
          description: 目標使用者 ID
          example: "abc123xyz"
        claimType:
          type: string
          enum: [admin, superAdmin, wilderness]
          description: 權限類型
          example: "admin"
        grant:
          type: boolean
          description: true=授予, false=撤銷
          example: true

    # ============ 標籤管理 ============
    DeleteTagRequest:
      type: object
      required:
        - tagId
        - tagName
      properties:
        tagId:
          type: string
          description: 要刪除的標籤 ID
          example: "tag123"
        tagName:
          type: string
          description: 標籤名稱（用於日誌記錄）
          example: "環保商店"

    # ============ Firestore 直接操作 (非 Cloud Function) ============
    # 以下為 Firestore SDK 操作的資料結構，供前端參考

    # 標籤 CRUD
    Tag:
      type: object
      required:
        - name
        - createdAt
        - createdBy
      properties:
        id:
          type: string
          readOnly: true
          description: 標籤 ID（自動產生）
        name:
          type: string
          minLength: 1
          maxLength: 50
          description: 標籤名稱（必須唯一）
          example: "環保商店"
        createdAt:
          type: string
          format: date-time
          description: 建立時間
        createdBy:
          type: string
          description: 建立者使用者 ID
        updatedAt:
          type: string
          format: date-time
          description: 最後更新時間

    # 平台設定
    PlatformSettings:
      type: object
      properties:
        defaultMapCenter:
          $ref: '#/components/schemas/GeoPoint'
        defaultZoomLevel:
          type: integer
          minimum: 1
          maximum: 20
          description: 預設地圖縮放層級
          example: 13
        reviewDeadlineDays:
          type: integer
          minimum: 1
          maximum: 30
          description: 審核期限（天）
          example: 3
        maxDailyUploads:
          type: integer
          minimum: 1
          maximum: 20
          description: 每日上傳限制
          example: 5
        updatedAt:
          type: string
          format: date-time
          description: 最後更新時間
        updatedBy:
          type: string
          description: 最後更新者使用者 ID

    GeoPoint:
      type: object
      required:
        - latitude
        - longitude
      properties:
        latitude:
          type: number
          minimum: -90
          maximum: 90
          description: 緯度
          example: 22.6273
        longitude:
          type: number
          minimum: -180
          maximum: 180
          description: 經度
          example: 120.3014

    # 使用者（擴展欄位）
    User:
      type: object
      properties:
        id:
          type: string
          description: 使用者 ID
        email:
          type: string
          format: email
          description: Email
        displayName:
          type: string
          description: 顯示名稱
        createdAt:
          type: string
          format: date-time
          description: 註冊時間
        isAdmin:
          type: boolean
          description: 是否為管理員
        isSuperAdmin:
          type: boolean
          description: 是否為超級管理員
        isWildernessPartner:
          type: boolean
          description: 是否為野外考察合作夥伴

    # ============ 回應格式 ============
    SuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true

    BatchOperationResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        affectedLocations:
          type: integer
          description: 受影響的地點數量
          example: 15

    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          description: 錯誤代碼
          example: "permission-denied"
        message:
          type: string
          description: 錯誤訊息
          example: "只有超級管理員可以執行此操作"

tags:
  - name: 使用者管理
    description: 使用者權限管理相關操作
  - name: 標籤管理
    description: 標籤 CRUD 和批次操作
